In [1]:
#I tried to add the scores from someother dataset but since we have sentiment score
#At leat we need some relevancy for that.
import pandas as pd
import numpy as np
import random

scoring = pd.read_csv('text_score.csv')
scoring.head()

      LABEL  SCORE
0  NEGATIVE  0.998
1  NEGATIVE  0.679
2  NEGATIVE  0.679
3  NEGATIVE  0.993
4  POSITIVE  0.999

In [2]:
#Make rating data from the Sentiment Score.
#Add feature Ratings.
scoring['Ratings'] = 0.0
labels = scoring['LABEL']
rates = scoring['Ratings']

for i in range(0, len(labels)):
    if labels[i] == 'POSITIVE': rates[i] = round(random.uniform(3,5),1)
    else: rates[i] = round(random.uniform(0,3),1)
#Using round function so that we could see the number with a format of X.X
scoring

<ipython-input-2-afb4139c9558>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  else: rates[i] = round(random.uniform(0,3),1)
<ipython-input-2-afb4139c9558>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if labels[i] == 'POSITIVE': rates[i] = round(random.uniform(3,5),1)

           LABEL  SCORE  Ratings
0       NEGATIVE  0.998      1.7
1       NEGATIVE  0.679      0.0
2       NEGATIVE  0.679      2.4
3       NEGATIVE  0.993      2.5
4       POSITIVE  0.999      3.3
...          ...    ...      ...
414800  NEGATIVE  0.993      1.0
414801  POSITIVE  0.999      4.5
414802  POSITIVE  0.999      3.8
414803  POSITIVE  0.999      3.3
414804  NEGATIVE  0.999      0.7

[414805 rows x 3 columns]

In [3]:
scoring.to_csv('scores.csv')